NotYetMozart2/config/routes.rb
NotYetMozart2::Application.routes.draw do



  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :songs
  resources :users

  resources :comments do
    member do
      get :flag
    end
  end

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy', as: :logout
  resources :sessions

  root :to => 'home#index'
end




#      root        /                         home#index

#     users GET    /users(.:format)          users#index
#           POST   /users(.:format)          users#create
#  new_user GET    /users/new(.:format)      users#new
# edit_user GET    /users/:id/edit(.:format) users#edit
#      user GET    /users/:id(.:format)      users#show
#           PUT    /users/:id(.:format)      users#update
#           DELETE /users/:id(.:format)      users#destroy

#     songs GET    /songs(.:format)          songs#index
#           POST   /songs(.:format)          songs#create
#  new_song GET    /songs/new(.:format)      songs#new
# edit_song GET    /songs/:id/edit(.:format) songs#edit
#      song GET    /songs/:id(.:format)      songs#show
#           PUT    /songs/:id(.:format)      songs#update
#           DELETE /songs/:id(.:format)      songs#destroy

#        login GET    /login(.:format)             sessions#new
#       logout GET    /logout(.:format)            sessions#destroy
#     sessions GET    /sessions(.:format)          sessions#index
#              POST   /sessions(.:format)          sessions#create
#  new_session GET    /sessions/new(.:format)      sessions#new
# edit_session GET    /sessions/:id/edit(.:format) sessions#edit
#      session GET    /sessions/:id(.:format)      sessions#show
#              PUT    /sessions/:id(.:format)      sessions#update
#              DELETE /sessions/:id(.:format)      sessions#destroy

NotYetMozart2/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :songs, dependent: :destroy
  has_many :comments, dependent: :destroy

  attr_accessible :background_image, :created_at, :email, :name, :password, :password_confirmation, :role, :user_image

  before_validation :set_default_role

  mount_uploader :user_image, UserImageUploader
  mount_uploader :background_image, BackgroundImageUploader

  validates :password, presence: true, on: :created
  validates :email, presence: true
  validates :email, uniqueness: true

  def role?(role_to_compare)
    self.role.to_s == role_to_compare.to_s #returns a boolean, whether a user has a certain rule. Is Nico an Admin? (True/False).
  end

  private
  def set_default_role
    self.role ||= :user
  end

end

NotYetMozart2/app/controllers/users_controller.rb
class UsersController < ApplicationController
load_and_authorize_resource


  # GET /users
  # GET /users.json
  def index
    @users = User.order(:created_at).page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
 def create
  @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id unless current_user
      redirect_to users_path, notice: "Signed up!"
    else
      render "new"
    end
  end


  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: 'User was successfully created.' }
  #       format.json { render json: @user, status: :created, location: @user }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

NotYetMozart2/app/helpers/users_helper.rb
module UsersHelper
end

NotYetMozart2/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :user_image %><br />
    <%= f.file_field :user_image %>
  </div>
  <div class="field">
    <%= f.label :background_image %><br />
    <%= f.file_field :background_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

NotYetMozart2/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Profile', @user %>

NotYetMozart2/app/views/users/index.html.erb
<h1></h1>
<br>
<br>
<br>
<br>
<br>

<table>
  <tr>
  <% if can? :manage, :all %>
    <th>User Image</th>
    <th>User name</th>
    <th>Email</th>
    <th>Role</th>
  <% end %>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><h4><div class="user_pic"><%= image_tag user.user_image.detail.url %></div></h4></td>
    <td><h4><%= link_to user.name, user %></h4></td>
    <% if can? :manage, :all %>
      <td><h4><%= user.email %></h4></td>
      <td><h4><%= user.role %></h4></td>
    <% end %>
  </tr>
<% end %>
</table>

<h4><%= paginate @users %></h4>
<br />

NotYetMozart2/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<br>

NotYetMozart2/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<style>
body {
  background: url(<%= @user.background_image.detail.url %>);
  background-size: cover;
}
</style>
<p>
  <h2><%= @user.name %></h2>
</p>

<p>
  <% if can? :view_role, User %>
        <b>Role:</b>
         <%= @user.role %>
  <% end %>
</p>


<p>
  <% if can? :view_email, User %>
      <b>Email:</b>
        <%= @user.email %>
  <% end %>
</p>

<p>
  <b>Rocking NYM since:</b>
  <%= @user.created_at.strftime('%B:%Y') %>
</p>

<p>
</p>

<p>
 <div class="user_pic"><%= image_tag @user.user_image.detail.url %></div>
</p>


<h1></h1>
<br>
<br>
<br>
<br>
<br>
<table>


<% @user.songs.each do |song| %>
  <tr>
    <td><%=link_to song.name, song_path(song) %></td>
    <td>
      <audio controls>
      <source src=<%= song.song_file.url %> type="audio/mpeg">
      </audio>
    </td>
    <td><div class="song_pic2"><%= image_tag song.song_image.thumb.url %></div></td>
    <% end %>
  </tr>
</table>
</br>




<%= link_to 'Delete Profile |', @user, method: :delete, data: { confirm: 'Are you sure you want to delete your NYM profile?' } if can? :destroy, @user%>
<%= link_to 'Edit |', edit_user_path(@user) if can? :edit, @user %>
<%= link_to 'All Users', users_path %>

<br>
<br>