NotYetMozart2/config/routes.rb
NotYetMozart2::Application.routes.draw do



  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :songs
  resources :users

  resources :comments do
    member do
      get :flag
    end
  end

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy', as: :logout
  resources :sessions

  root :to => 'home#index'
end




#      root        /                         home#index

#     users GET    /users(.:format)          users#index
#           POST   /users(.:format)          users#create
#  new_user GET    /users/new(.:format)      users#new
# edit_user GET    /users/:id/edit(.:format) users#edit
#      user GET    /users/:id(.:format)      users#show
#           PUT    /users/:id(.:format)      users#update
#           DELETE /users/:id(.:format)      users#destroy

#     songs GET    /songs(.:format)          songs#index
#           POST   /songs(.:format)          songs#create
#  new_song GET    /songs/new(.:format)      songs#new
# edit_song GET    /songs/:id/edit(.:format) songs#edit
#      song GET    /songs/:id(.:format)      songs#show
#           PUT    /songs/:id(.:format)      songs#update
#           DELETE /songs/:id(.:format)      songs#destroy

#        login GET    /login(.:format)             sessions#new
#       logout GET    /logout(.:format)            sessions#destroy
#     sessions GET    /sessions(.:format)          sessions#index
#              POST   /sessions(.:format)          sessions#create
#  new_session GET    /sessions/new(.:format)      sessions#new
# edit_session GET    /sessions/:id/edit(.:format) sessions#edit
#      session GET    /sessions/:id(.:format)      sessions#show
#              PUT    /sessions/:id(.:format)      sessions#update
#              DELETE /sessions/:id(.:format)      sessions#destroy

NotYetMozart2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Audiowide' rel='stylesheet' type='text/css'>
  <title>NotYetMozart2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>



  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" <%= link_to 'Not Yet Mozart', root_path %></a>
      </div>


      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Songs', songs_path %></li>
          <li class="active"><%= link_to 'Users', users_path %></li>
            <% if can? :manage, :all %>
              <li><%= link_to 'Flagged Comments', comments_path %></li>
            <% end %>
        </ul>

        <%# HERE COMES THE SEARCH BAR-%>

        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>

        <%# BUTTONS ON THE RIGHT SIDE %>

        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <% if can? :create, Song %>
                <li><%= link_to 'New Song', new_song_path %></li>
            <% end %>
              <li><%= link_to current_user.name, current_user %></li>
              <li><%= link_to 'Logout', logout_path %></li>
           <% else %>
              <li><%= link_to 'Sign Up', new_user_path %></li>
              <li><%= link_to 'Login', login_path %></li>
          <% end %>

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>






  <div class="container">
    <%= yield %>
  </div>

</body>
</html>