NotYetMozart2/config/routes.rb
NotYetMozart2::Application.routes.draw do



  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :songs
  resources :users

  resources :comments do
    member do
      get :flag
    end
  end

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy', as: :logout
  resources :sessions

  root :to => 'home#index'
end




#      root        /                         home#index

#     users GET    /users(.:format)          users#index
#           POST   /users(.:format)          users#create
#  new_user GET    /users/new(.:format)      users#new
# edit_user GET    /users/:id/edit(.:format) users#edit
#      user GET    /users/:id(.:format)      users#show
#           PUT    /users/:id(.:format)      users#update
#           DELETE /users/:id(.:format)      users#destroy

#     songs GET    /songs(.:format)          songs#index
#           POST   /songs(.:format)          songs#create
#  new_song GET    /songs/new(.:format)      songs#new
# edit_song GET    /songs/:id/edit(.:format) songs#edit
#      song GET    /songs/:id(.:format)      songs#show
#           PUT    /songs/:id(.:format)      songs#update
#           DELETE /songs/:id(.:format)      songs#destroy

#        login GET    /login(.:format)             sessions#new
#       logout GET    /logout(.:format)            sessions#destroy
#     sessions GET    /sessions(.:format)          sessions#index
#              POST   /sessions(.:format)          sessions#create
#  new_session GET    /sessions/new(.:format)      sessions#new
# edit_session GET    /sessions/:id/edit(.:format) sessions#edit
#      session GET    /sessions/:id(.:format)      sessions#show
#              PUT    /sessions/:id(.:format)      sessions#update
#              DELETE /sessions/:id(.:format)      sessions#destroy

NotYetMozart2/app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  attr_accessible :created_at, :name, :song_file, :song_image, :user_id
  mount_uploader :song_image, SongImageUploader
  mount_uploader :song_file, SongFileUploader

  validates :name, presence: true
  validates :song_file, presence: true
end

NotYetMozart2/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.order(:created_at).page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])
    @comment = Comment.new()

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])
    @song.user = current_user

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end
end

NotYetMozart2/app/helpers/songs_helper.rb
module SongsHelper
end

NotYetMozart2/app/views/songs/_comment_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= hidden_field_tag(:song_id, @song.id) %>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

NotYetMozart2/app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :song_file %><br />
    <%= f.file_field :song_file %>
  </div>
  <div class="field">
    <%= f.label :song_image %><br />
    <%= f.file_field :song_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

NotYetMozart2/app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>


<%= link_to 'Back', @song %>

NotYetMozart2/app/views/songs/index.html.erb
<h1></h1>
<br>
<br>
<br>
<br>
<br>
<table>




<% @songs.each do |song| %>
  <tr>
    <td><div class="user_pic"><%= image_tag song.user.user_image.detail.url %></div></li></td>
    <td><h4><%= link_to song.user.name, song.user %></h4></td>
    <td><h4><%= link_to song.name, song %></h4></td>
    <td>
        <audio controls>
            <source src=<%= song.song_file.url %> type="audio/mpeg">
        </audio>
    </td>


  </tr>
<% end %>
</table>

<br />


<h4><%= paginate @songs %></h4>
<br />
<br>

NotYetMozart2/app/views/songs/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', songs_path %>

NotYetMozart2/app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>
<style>
body {
  background: url(<%= @song.user.background_image.detail.url %>);
  background-size: cover;
}
</style>
<p>

  <h2><%= @song.name %></h2>
  <h3><%= link_to @song.user.name, @song.user %></h3>
</p>

<p>
  <audio controls>
      <source src=<%= @song.song_file.url %> type="audio/mpeg">
  </audio>
</p>

<p>
  <b>Created at:</b>
  <%= @song.created_at.strftime('%B:%Y') %>
</p>


<p>
 <div class="song_pic"><%= image_tag @song.song_image.detail.url %></div>
</p>

<% if can? :create, Song %>
  <%= render 'comment_form' %>

  <% @song.comments.each do |comment| %>
    <tr>
      <br>
      <td><%= link_to comment.user.name, comment.user %></td>
      <td><%= comment.comment %></td>
        <% if comment.flag  %> 
          <td><span class="flagged">Flagged</span></td>
        <% else %> 
          <%= link_to 'Report', flag_comment_path(comment), data: { confirm: 'Flag comment as innapropriate?' } %> 
          <% end %>
      <td><%= link_to 'Edit', edit_comment_path(comment) if can? :edit, comment %></td>
      <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, comment %></td>
    </tr>
    <br>
  <% end %>
<% end %>




<br>
<%= link_to 'Delete Song |', @song, method: :delete, data: { confirm: 'Are you sure you want to delete this song?' } if can? :destroy, @song%>
<%= link_to 'Edit |', edit_song_path(@song) if can? :edit, @song%>
<%= link_to 'All Songs', songs_path %>
<br>
<br>
<br>